import React from "react";
import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

const Layout = ({ children }) => {
    return (
        <>
            {/* The Head */}
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/hulu.png' />
            </Head>

            {/* The Header */}
            <Header />

            {/* The Body */}
            {children}

            {/* The Footer */}
            <Footer />
        </>
    );
};

export default Layout;
